name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      run: |
        docker build -t my-react-app:latest .
        docker tag my-react-app:latest 65.2.35.50:5000/my-react-app:latest
        docker push 65.2.35.50:5000/my-react-app:latest

    - name: SSH to EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 65.2.35.50
        username: ec2-user
        #key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull 65.2.35.50:5000/my-react-app:latest
          docker run -d -p 80:3000 65.2.35.50:5000/my-react-app:latest
